package com.example.auctionapp.model;

import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;

public class BidTransactionTest {

    @Test
    public void testBidTransactionCreation() {
        // Arrange
        Member bidder = new Member("Bob Bidder", "555-1234", "bob@email.com", "bob99", "pass", "123 St");

        // Act
        BidTransaction bid = new BidTransaction(bidder, 500.0);

        // Assert
        assertEquals(500.0, bid.getBidAmount(), "Bid amount should map correctly");
        assertEquals(bidder, bid.getBidder(), "Bid must be tied to the correct Member object");

        // Ensure the timestamp was automatically generated and is very recent (within the last 1 second)
        assertNotNull(bid.getTime(), "Time must be auto-generated by the constructor");
        assertTrue(bid.getTime().isAfter(LocalDateTime.now().minusSeconds(1)), "Timestamp must be real-time");
    }
}